### ISSUE TITLE
Won't let me log in

### ISSUE THREAD

**Issue by anniexoxi** [tinuh/grade-melon#5]
I've already made it a bookmark, and I open it in safari on my phone, but nothing shows up whenever i try to type in my credentials in the boxes. I've been trying for 2 days, thank you. _

very cool app though, ever since gradeview left so I'm trying to use this!

**Comment by tinuh** [comment]
Hey, over the past few days multiple people have reported this to me, so I will look into it once I'm able to replicate it.

**Comment by tinuh** [comment]
hey this should've been fixed in my latest commit, let me know if this issue persists.
